### ISSUE TITLE
The website is stuck in "LOADING..." state on Firefox

### ISSUE THREAD

**Issue by InvisibleRain** [LWJGL/lwjgl3-www#116]
Firefox version: 94.0.2 (32-bit)
Host OS: Windows 10
Link: https://www.lwjgl.org/
Screenshot:
![image](https://user-images.githubusercontent.com/47538801/144027487-ec086ce8-c24b-4631-b4c4-d9f84ed6689b.png)

Works fine in chromium though

**Comment by InvisibleRain** [comment]
Error in debug console:
```
Uncaught DOMException: CSSStyleSheet.cssRules getter: Not allowed to access cross-origin stylesheet main.ce3b43d6d1557e39.js:1
    n https://www.lwjgl.org/js/main.ce3b43d6d1557e39.js:1
    z https://www.lwjgl.org/js/main.ce3b43d6d1557e39.js:1
    n https://www.lwjgl.org/js/main.ce3b43d6d1557e39.js:1
    c https://www.lwjgl.org/js/main.ce3b43d6d1557e39.js:1
    t https://www.lwjgl.org/js/main.ce3b43d6d1557e39.js:1
    Z https://www.lwjgl.org/js/main.ce3b43d6d1557e39.js:1
    9707 https://www.lwjgl.org/js/main.ce3b43d6d1557e39.js:1
    e https://www.lwjgl.org/js/main.ce3b43d6d1557e39.js:1
    <anonymous> https://www.lwjgl.org/js/main.ce3b43d6d1557e39.js:1
    <anonymous> https://www.lwjgl.org/js/main.ce3b43d6d1557e39.js:1
    <anonymous> https://www.lwjgl.org/js/main.ce3b43d6d1557e39.js:1
```

**Comment by apostolos** [comment]
I'm quite certain this error is caused by an extension installed in your copy of Firefox. Is it possible to send me a list of your installed & activated extensions? Can you also try disabling your extensions and try to load the site again?

It's probably an extension that messes with the page styling, so you might want to just disable those. I'm guessing an extension that injects external stylesheets (from 3rd party origins)? It's important to understand what's causing this so we can try to find a workaround for other people that might face the same or similar problems.

For the record, I've confirmed that the site works in Firefox (tested in multiple computers).
Screenshot from Browserstack (Win10, Firefox 94):
![image](https://user-images.githubusercontent.com/41679/144046535-dfa16157-8ae8-4323-8307-fa05c5cc6bbd.png)

**Comment by InvisibleRain** [comment]
Indeed, [Vim Vixen](https://addons.mozilla.org/en-US/firefox/addon/vim-vixen/) was the extension that caused the problem. Blacklisting the website didn't help, so I had to turn the extension off completely. There's already an [issue](https://github.com/ueokande/vim-vixen/issues/761) regarding that problem
