### ISSUE TITLE
What If I enable mangling process?

### ISSUE THREAD

**Issue by ufukomer** [LWJGL/lwjgl3-www#31]
Do you know what causes the following error when I enable mangling? Won't it be possible to accomplish mangling with a specific options? I'm asking because after your webpack and process-manifest.js updates, my total bundle size increased by 30Kb (gzipped).

<img width="461" alt="screen shot 2017-09-08 at 11 25 15 am" src="https://user-images.githubusercontent.com/7649229/30202842-82caa958-9488-11e7-8197-c0aed37fa82b.png">

https://github.com/LWJGL/lwjgl3-www/blob/master/scripts/process-manifest.js#L121-L133

_Additinal Question: Should I open another issue about that I can't see the exact location of the errors even if I define _devtool_ prop in webpack config (sourcemap)? I'm also trying to figure out that case. I may send pr If I can._

**Comment by apostolos** [comment]
Are you talking about LWJGL's main.js? That should have dropped in size, not increased. The current production build is just 111KB gzipped, it has never been that small.

Changes in the build process were made to only include the required core-js modules instead of the whole package. See [.babelrc](https://github.com/LWJGL/lwjgl3-www/blob/master/.babelrc)'s production configuration.

_Sourcemap information must being stripped away by Uglify. I think webpack and uglify-js@3 must work together to preserve original source information, however I've never really worked with source mapping and can't help you. If you find a way to do it, please send PR!_

**Comment by apostolos** [comment]
Mangling is enabled by default in UglifyJS3, you don't have to pass any specific options.

I was going through the commits around the same time I changed the build process. One thing that might have altered the build size is the conversion from using aphrodite to styled-components. Styled-components has a heavier runtime than I thought. That might explain the increase in the bundle size that you are seeing.

I decided against using styled-components after all and I've ported everything again, this time in [emotion](https://emotion.sh/). The final production build dropped from 111KB to 104KB. The total bundle size (all JS files) is now under 200KB gzipped.
